baseURL = "http://example.org/"
languageCode = "en-us"
title = "Evening Tide"

[permalinks]
  blog = "/:filename/"

[params]
    dateFormat = "Jan 2, 2006"
    homeText = "I was satisfied with haiku until I met you, jar of octopus, cuckoo’s cry, 5-7-5..."

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3